// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/classifier.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Classifier_GetMainContext_FullMethodName = "/proto.Classifier/GetMainContext"
)

// ClassifierClient is the client API for Classifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassifierClient interface {
	GetMainContext(ctx context.Context, in *BotRequest, opts ...grpc.CallOption) (*Response, error)
}

type classifierClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifierClient(cc grpc.ClientConnInterface) ClassifierClient {
	return &classifierClient{cc}
}

func (c *classifierClient) GetMainContext(ctx context.Context, in *BotRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Classifier_GetMainContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierServer is the server API for Classifier service.
// All implementations must embed UnimplementedClassifierServer
// for forward compatibility.
type ClassifierServer interface {
	GetMainContext(context.Context, *BotRequest) (*Response, error)
	mustEmbedUnimplementedClassifierServer()
}

// UnimplementedClassifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassifierServer struct{}

func (UnimplementedClassifierServer) GetMainContext(context.Context, *BotRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMainContext not implemented")
}
func (UnimplementedClassifierServer) mustEmbedUnimplementedClassifierServer() {}
func (UnimplementedClassifierServer) testEmbeddedByValue()                    {}

// UnsafeClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifierServer will
// result in compilation errors.
type UnsafeClassifierServer interface {
	mustEmbedUnimplementedClassifierServer()
}

func RegisterClassifierServer(s grpc.ServiceRegistrar, srv ClassifierServer) {
	// If the following call panics, it indicates UnimplementedClassifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Classifier_ServiceDesc, srv)
}

func _Classifier_GetMainContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).GetMainContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classifier_GetMainContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).GetMainContext(ctx, req.(*BotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Classifier_ServiceDesc is the grpc.ServiceDesc for Classifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Classifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Classifier",
	HandlerType: (*ClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMainContext",
			Handler:    _Classifier_GetMainContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/classifier.proto",
}
