// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/classifier.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotRequest) Reset() {
	*x = BotRequest{}
	mi := &file_proto_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotRequest) ProtoMessage() {}

func (x *BotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotRequest.ProtoReflect.Descriptor instead.
func (*BotRequest) Descriptor() ([]byte, []int) {
	return file_proto_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *BotRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_proto_classifier_proto protoreflect.FileDescriptor

const file_proto_classifier_proto_rawDesc = "" +
	"\n" +
	"\x16proto/classifier.proto\x12\x05proto\"\"\n" +
	"\n" +
	"BotRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output2B\n" +
	"\n" +
	"Classifier\x124\n" +
	"\x0eGetMainContext\x12\x11.proto.BotRequest\x1a\x0f.proto.ResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_classifier_proto_rawDescOnce sync.Once
	file_proto_classifier_proto_rawDescData []byte
)

func file_proto_classifier_proto_rawDescGZIP() []byte {
	file_proto_classifier_proto_rawDescOnce.Do(func() {
		file_proto_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_classifier_proto_rawDesc), len(file_proto_classifier_proto_rawDesc)))
	})
	return file_proto_classifier_proto_rawDescData
}

var file_proto_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_classifier_proto_goTypes = []any{
	(*BotRequest)(nil), // 0: proto.BotRequest
	(*Response)(nil),   // 1: proto.Response
}
var file_proto_classifier_proto_depIdxs = []int32{
	0, // 0: proto.Classifier.GetMainContext:input_type -> proto.BotRequest
	1, // 1: proto.Classifier.GetMainContext:output_type -> proto.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_classifier_proto_init() }
func file_proto_classifier_proto_init() {
	if File_proto_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_classifier_proto_rawDesc), len(file_proto_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_classifier_proto_goTypes,
		DependencyIndexes: file_proto_classifier_proto_depIdxs,
		MessageInfos:      file_proto_classifier_proto_msgTypes,
	}.Build()
	File_proto_classifier_proto = out.File
	file_proto_classifier_proto_goTypes = nil
	file_proto_classifier_proto_depIdxs = nil
}
