[project]
name = "bot3"
version = "0.1.0"
description = "bot component for interaction with social media API"
authors = [{ name = "John321Blacksmith", email = "kuzmichevi321@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
]
